version: '3.2'

services:
  prometheus:
    container_name: prometheus
    image: registry.cn-hangzhou.aliyuncs.com/k8ops/prometheus:v2.35.0
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/alerts:/etc/prometheus/alerts
      - type: bind
        source: ./config/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: registry.cn-hangzhou.aliyuncs.com/k8ops/grafana:8.1.2
    restart: unless-stopped
    ports:
      - 3000:3000
    user: '472'
    volumes:
      - /data/opsmetrics/data/grafana/data:/var/lib/grafana
      - ./config/grafana:/etc/grafana

  prometheus-alert:
    container_name: prometheus-alert
    image: registry.cn-hangzhou.aliyuncs.com/k8ops/prometheus-alert:v4.8.2
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: /data/opsmetrics/data/prometheus-alert/db/PrometheusAlertDB.db
        target: /app/db/PrometheusAlertDB.db
      - type: bind
        source: ./config/prometheus-alert/docker-entrypoint.sh
        target: /app/docker-entrypoint.sh
    environment:
      - PA_LOGIN_USER=admin
      - PA_LOGIN_PASSWORD=prometheusalert
      - PA_TITLE=PrometheusAlert
      - PA_OPEN_DINGDING=1
      - PA_OPEN_WEIXIN=1
      - PA_OPEN_FEISHU=1

networks:
  default:
    name: opsmetrics
