version: '3.2'

services:
  node-exporter:
    image: registry.cn-hangzhou.aliyuncs.com/k8ops/node-exporter:v1.3.1
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  cadvisor:
    image: registry.cn-hangzhou.aliyuncs.com/k8ops/cadvisor:v0.36.0
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "9102:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

networks:
  default:
    external:
      name: opsmetrics
